services:
  app_proxy:
    environment:
      APP_HOST: dissfall-app-store-freqtrade_server_1
      APP_PORT: 8084

  server:
    image: freqtradeorg/freqtrade:2024.6
    volumes:
      - ${UMBREL_ROOT}/data/storage/freqtrade:/freqtrade/user_data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
