services:
  app_proxy:
    environment:
      APP_HOST: dissfall-app-store-homepage_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/gethomepage/homepage:v0.9.2
    volumes:
      - ${UMBREL_ROOT}/data/storage/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
