services:
  app_proxy:
    environment:
      APP_HOST: dissfall-app-store-doctobot_server_1
      APP_PORT: 5001

  server:
    image: ghcr.io/dissfall/doctobot:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
