services:
  app_proxy:
    environment:
      APP_HOST: dissfall-app-store-cryptpad_server_1
      APP_PORT: 3000

  server:
    image: cryptpad/cryptpad:version-2025.3.0
    environment:
      - CPAD_MAIN_DOMAIN=http://cryptpad.umbrel.local
      - CPAD_SANDBOX_DOMAIN=http://cryptpads.umbrel.local
      - CPAD_CONF=/cryptpad/config/config.js
    volumes:
      - ${UMBREL_ROOT}/data/storage/cryptpad/config:/cryptpad/config
      - ${UMBREL_ROOT}/data/storage/cryptpad/blob:/cryptpad/blob
      - ${UMBREL_ROOT}/data/storage/cryptpad/block:/cryptpad/block
      - ${UMBREL_ROOT}/data/storage/cryptpad/customise:/cryptpad/customise
      - ${UMBREL_ROOT}/data/storage/cryptpad/data:/cryptpad/data
      - ${UMBREL_ROOT}/data/storage/cryptpad/datastore:/cryptpad/datastore
      - ${UMBREL_ROOT}/data/storage/cryptpad/onlyoffice-dist:/cryptpad/www/common/onlyoffice/dist
      - ${UMBREL_ROOT}/data/storage/cryptpad/onlyoffice-conf:/cryptpad/onlyoffice-conf
