services:
  app_proxy:
    environment:
      APP_HOST: dissfall-app-store-octobot_server_1
      APP_PORT: 5001

  server:
    image: drakkarsoftware/octobot:1.0.10
    volumes:
      - ${APP_DATA_DIR}/data:/octobot
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
