services:
  app_proxy:
    environment:
      APP_HOST: dissfall-app-store-octobot_server_1
      APP_PORT: 5001

  server:
    image: drakkarsoftware/octobot:1.0.10
    volumes:
      - ${APP_DATA_DIR}/data/logs:/octobot/logs
      - ${APP_DATA_DIR}/data/backtesting:/octobot/backtesting
      - ${APP_DATA_DIR}/data/tentacles:/octobot/tentacles
      - ${APP_DATA_DIR}/data/user:/octobot/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
